//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Service_POI.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Search_LandmarkSoap")]
    public interface Search_LandmarkSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search(string keyword, string AdminLevel3, string AdminLevel2, string AdminLevel1, string PostCode, string AdminLevel4, string category, string tag, string lat, string lon, string radius, string RowsPerPage, string PageNumber, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoComplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AutoComplete(string keyword, string numreturn, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Identify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Identify(string lat, string lon, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_Nearby", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Search_Nearby(string lat, string lon, string distance, string numreturn, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetIP();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Search_LandmarkSoapChannel : Search_Service_POI.ServiceReference1.Search_LandmarkSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Search_LandmarkSoapClient : System.ServiceModel.ClientBase<Search_Service_POI.ServiceReference1.Search_LandmarkSoap>, Search_Service_POI.ServiceReference1.Search_LandmarkSoap {
        
        public Search_LandmarkSoapClient() {
        }
        
        public Search_LandmarkSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Search_LandmarkSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Search_LandmarkSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Search_LandmarkSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Search(string keyword, string AdminLevel3, string AdminLevel2, string AdminLevel1, string PostCode, string AdminLevel4, string category, string tag, string lat, string lon, string radius, string RowsPerPage, string PageNumber, string token) {
            return base.Channel.Search(keyword, AdminLevel3, AdminLevel2, AdminLevel1, PostCode, AdminLevel4, category, tag, lat, lon, radius, RowsPerPage, PageNumber, token);
        }
        
        public System.Data.DataTable AutoComplete(string keyword, string numreturn, string token) {
            return base.Channel.AutoComplete(keyword, numreturn, token);
        }
        
        public System.Data.DataTable Identify(string lat, string lon, string token) {
            return base.Channel.Identify(lat, lon, token);
        }
        
        public string Search_Nearby(string lat, string lon, string distance, string numreturn, string token) {
            return base.Channel.Search_Nearby(lat, lon, distance, numreturn, token);
        }
        
        public string GetIP() {
            return base.Channel.GetIP();
        }
    }
}
