//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Service_POI.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.identSoap")]
    public interface identSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SnapAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SnapAdmin(string lat, string lon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SnapPublicArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SnapPublicArea(string lat, string lon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SnapHydro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SnapHydro(string lat, string lon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_SnapLtrans_KM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search_SnapLtrans_KM(string lat, string lon, string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search_SnapLtrans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Search_SnapLtrans(string lat, string lon, string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoadSnapping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RoadSnapping(string Path, string Info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RoadSnapping_R", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RoadSnapping_R(string Path, string Radius, string Info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface identSoapChannel : Search_Service_POI.ServiceReference3.identSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class identSoapClient : System.ServiceModel.ClientBase<Search_Service_POI.ServiceReference3.identSoap>, Search_Service_POI.ServiceReference3.identSoap {
        
        public identSoapClient() {
        }
        
        public identSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public identSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public identSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public identSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable SnapAdmin(string lat, string lon) {
            return base.Channel.SnapAdmin(lat, lon);
        }
        
        public System.Data.DataTable SnapPublicArea(string lat, string lon) {
            return base.Channel.SnapPublicArea(lat, lon);
        }
        
        public System.Data.DataTable SnapHydro(string lat, string lon) {
            return base.Channel.SnapHydro(lat, lon);
        }
        
        public System.Data.DataTable Search_SnapLtrans_KM(string lat, string lon, string radius) {
            return base.Channel.Search_SnapLtrans_KM(lat, lon, radius);
        }
        
        public System.Data.DataTable Search_SnapLtrans(string lat, string lon, string radius) {
            return base.Channel.Search_SnapLtrans(lat, lon, radius);
        }
        
        public System.Data.DataTable RoadSnapping(string Path, string Info) {
            return base.Channel.RoadSnapping(Path, Info);
        }
        
        public System.Data.DataTable RoadSnapping_R(string Path, string Radius, string Info) {
            return base.Channel.RoadSnapping_R(Path, Radius, Info);
        }
    }
}
