//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Service_POI.ServiceReference_soundex {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_soundex.SoundexSoap")]
    public interface SoundexSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Thai_soundex", ReplyAction="*")]
        Search_Service_POI.ServiceReference_soundex.Thai_soundexResponse Thai_soundex(Search_Service_POI.ServiceReference_soundex.Thai_soundexRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Thai_soundexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Thai_soundex", Namespace="http://tempuri.org/", Order=0)]
        public Search_Service_POI.ServiceReference_soundex.Thai_soundexRequestBody Body;
        
        public Thai_soundexRequest() {
        }
        
        public Thai_soundexRequest(Search_Service_POI.ServiceReference_soundex.Thai_soundexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Thai_soundexRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public Thai_soundexRequestBody() {
        }
        
        public Thai_soundexRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Thai_soundexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Thai_soundexResponse", Namespace="http://tempuri.org/", Order=0)]
        public Search_Service_POI.ServiceReference_soundex.Thai_soundexResponseBody Body;
        
        public Thai_soundexResponse() {
        }
        
        public Thai_soundexResponse(Search_Service_POI.ServiceReference_soundex.Thai_soundexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Thai_soundexResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Thai_soundexResult;
        
        public Thai_soundexResponseBody() {
        }
        
        public Thai_soundexResponseBody(string Thai_soundexResult) {
            this.Thai_soundexResult = Thai_soundexResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoundexSoapChannel : Search_Service_POI.ServiceReference_soundex.SoundexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoundexSoapClient : System.ServiceModel.ClientBase<Search_Service_POI.ServiceReference_soundex.SoundexSoap>, Search_Service_POI.ServiceReference_soundex.SoundexSoap {
        
        public SoundexSoapClient() {
        }
        
        public SoundexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoundexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoundexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoundexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Search_Service_POI.ServiceReference_soundex.Thai_soundexResponse Search_Service_POI.ServiceReference_soundex.SoundexSoap.Thai_soundex(Search_Service_POI.ServiceReference_soundex.Thai_soundexRequest request) {
            return base.Channel.Thai_soundex(request);
        }
        
        public string Thai_soundex(string input) {
            Search_Service_POI.ServiceReference_soundex.Thai_soundexRequest inValue = new Search_Service_POI.ServiceReference_soundex.Thai_soundexRequest();
            inValue.Body = new Search_Service_POI.ServiceReference_soundex.Thai_soundexRequestBody();
            inValue.Body.input = input;
            Search_Service_POI.ServiceReference_soundex.Thai_soundexResponse retVal = ((Search_Service_POI.ServiceReference_soundex.SoundexSoap)(this)).Thai_soundex(inValue);
            return retVal.Body.Thai_soundexResult;
        }
    }
}
