//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Service_POI.ServiceReference_textAnalytic {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_textAnalytic.WebService_searchSoap")]
    public interface WebService_searchSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAdmin1Thai", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CheckAdmin1Thai(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_searchSoapChannel : Search_Service_POI.ServiceReference_textAnalytic.WebService_searchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_searchSoapClient : System.ServiceModel.ClientBase<Search_Service_POI.ServiceReference_textAnalytic.WebService_searchSoap>, Search_Service_POI.ServiceReference_textAnalytic.WebService_searchSoap {
        
        public WebService_searchSoapClient() {
        }
        
        public WebService_searchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_searchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_searchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_searchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable CheckAdmin1Thai(string keyword) {
            return base.Channel.CheckAdmin1Thai(keyword);
        }
    }
}
